# Generated by Django 3.1.1 on 2021-05-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compose_name', models.TextField(default=None, verbose_name='编')),
                ('arrange_name', models.TextField(default=None, verbose_name='分编')),
                ('chapter_name', models.TextField(default=None, verbose_name='章')),
                ('section_name', models.TextField(default=None, verbose_name='节')),
                ('provision_name', models.TextField(default=None, verbose_name='条')),
                ('content', models.TextField(default=None, verbose_name='条文内容')),
            ],
        ),
    ]
